spring:
  # The below property will let this application fetch properties from Config Server.
  # After adding the Config Client dependency we have made this service as a Config Client
  config:
    import: configserver:http://localhost:8086
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: Sarthak@123
  application:
    name: HotelService
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

server:
  port: 8082

# We are commenting below properties as, these will be picked from
# the Config Server(GitHub(microservice-config))

#eureka:
#  instance:
#    prefer-ip-address: true
#    # The below property will registry this microservice with eureka server as a client
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8084/eureka

