spring:
  application:
    name: ServiceRegistry
server:
  port: 8084
eureka:
  instance:
    hostname: localhost
    # The below property will make sure that the eureka server is not registered by its own
    #  and could not fetch service registry. By-default both properties are true
  client:
    register-with-eureka: false
    fetch-registry: false

